---

- name: Ensure ssh server is installed
  ansible.builtin.package:
    name: openssh-server
    state: present

- name: Create sshd_config file
  ansible.builtin.include_tasks: template_config.yaml
