---
- name: Converge
  hosts: all

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

    - name: Include role
      ansible.builtin.include_role:
        name: ansible-role-openssh
        tasks_from: main
